package com.samchat.common.beans.auto.db.mapper;

import com.samchat.common.beans.auto.db.entitybeans.TAdvertisementSendLog;
import com.samchat.common.beans.auto.db.entitybeans.TAdvertisementSendLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAdvertisementSendLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_send_log
     *
     * @mbggenerated
     */
    int countByExample(TAdvertisementSendLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_send_log
     *
     * @mbggenerated
     */
    int deleteByExample(TAdvertisementSendLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_send_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long log_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_send_log
     *
     * @mbggenerated
     */
    int insert(TAdvertisementSendLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_send_log
     *
     * @mbggenerated
     */
    int insertSelective(TAdvertisementSendLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_send_log
     *
     * @mbggenerated
     */
    List<TAdvertisementSendLog> selectByExample(TAdvertisementSendLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_send_log
     *
     * @mbggenerated
     */
    TAdvertisementSendLog selectByPrimaryKey(Long log_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_send_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TAdvertisementSendLog record, @Param("example") TAdvertisementSendLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_send_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TAdvertisementSendLog record, @Param("example") TAdvertisementSendLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_send_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TAdvertisementSendLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_send_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TAdvertisementSendLog record);
}