package com.samchat.common.beans.auto.db.mapper;

import com.samchat.common.beans.auto.db.entitybeans.TAdvertisementContent;
import com.samchat.common.beans.auto.db.entitybeans.TAdvertisementContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAdvertisementContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_content
     *
     * @mbggenerated
     */
    int countByExample(TAdvertisementContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_content
     *
     * @mbggenerated
     */
    int deleteByExample(TAdvertisementContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long ads_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_content
     *
     * @mbggenerated
     */
    int insert(TAdvertisementContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_content
     *
     * @mbggenerated
     */
    int insertSelective(TAdvertisementContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_content
     *
     * @mbggenerated
     */
    List<TAdvertisementContent> selectByExample(TAdvertisementContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_content
     *
     * @mbggenerated
     */
    TAdvertisementContent selectByPrimaryKey(Long ads_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_content
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TAdvertisementContent record, @Param("example") TAdvertisementContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_content
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TAdvertisementContent record, @Param("example") TAdvertisementContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TAdvertisementContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TAdvertisementContent record);
}