package com.samchat.common.beans.auto.db.mapper;

import com.samchat.common.beans.auto.db.entitybeans.TContactUser;
import com.samchat.common.beans.auto.db.entitybeans.TContactUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TContactUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contact_user
     *
     * @mbggenerated
     */
    int countByExample(TContactUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contact_user
     *
     * @mbggenerated
     */
    int deleteByExample(TContactUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contact_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long contact_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contact_user
     *
     * @mbggenerated
     */
    int insert(TContactUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contact_user
     *
     * @mbggenerated
     */
    int insertSelective(TContactUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contact_user
     *
     * @mbggenerated
     */
    List<TContactUser> selectByExample(TContactUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contact_user
     *
     * @mbggenerated
     */
    TContactUser selectByPrimaryKey(Long contact_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contact_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TContactUser record, @Param("example") TContactUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contact_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TContactUser record, @Param("example") TContactUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contact_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TContactUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contact_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TContactUser record);
}