package com.samchat.common.beans.auto.db.mapper;

import com.samchat.common.beans.auto.db.entitybeans.TOaFollow;
import com.samchat.common.beans.auto.db.entitybeans.TOaFollowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TOaFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_follow
     *
     * @mbggenerated
     */
    int countByExample(TOaFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_follow
     *
     * @mbggenerated
     */
    int deleteByExample(TOaFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_follow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long follow_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_follow
     *
     * @mbggenerated
     */
    int insert(TOaFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_follow
     *
     * @mbggenerated
     */
    int insertSelective(TOaFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_follow
     *
     * @mbggenerated
     */
    List<TOaFollow> selectByExample(TOaFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_follow
     *
     * @mbggenerated
     */
    TOaFollow selectByPrimaryKey(Long follow_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_follow
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TOaFollow record, @Param("example") TOaFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_follow
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TOaFollow record, @Param("example") TOaFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_follow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TOaFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_follow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TOaFollow record);
}