package com.samchat.common.beans.auto.db.mapper;

import com.samchat.common.beans.auto.db.entitybeans.TQuestionPopularRequests;
import com.samchat.common.beans.auto.db.entitybeans.TQuestionPopularRequestsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TQuestionPopularRequestsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_popular_requests
     *
     * @mbggenerated
     */
    int countByExample(TQuestionPopularRequestsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_popular_requests
     *
     * @mbggenerated
     */
    int deleteByExample(TQuestionPopularRequestsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_popular_requests
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long popular_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_popular_requests
     *
     * @mbggenerated
     */
    int insert(TQuestionPopularRequests record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_popular_requests
     *
     * @mbggenerated
     */
    int insertSelective(TQuestionPopularRequests record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_popular_requests
     *
     * @mbggenerated
     */
    List<TQuestionPopularRequests> selectByExample(TQuestionPopularRequestsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_popular_requests
     *
     * @mbggenerated
     */
    TQuestionPopularRequests selectByPrimaryKey(Long popular_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_popular_requests
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TQuestionPopularRequests record, @Param("example") TQuestionPopularRequestsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_popular_requests
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TQuestionPopularRequests record, @Param("example") TQuestionPopularRequestsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_popular_requests
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TQuestionPopularRequests record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_popular_requests
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TQuestionPopularRequests record);
}