package com.samchat.common.beans.auto.db.mapper;

import com.samchat.common.beans.auto.db.entitybeans.TSysConfigs;
import com.samchat.common.beans.auto.db.entitybeans.TSysConfigsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSysConfigsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    int countByExample(TSysConfigsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    int deleteByExample(TSysConfigsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer param_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    int insert(TSysConfigs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    int insertSelective(TSysConfigs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    List<TSysConfigs> selectByExample(TSysConfigsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    TSysConfigs selectByPrimaryKey(Integer param_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TSysConfigs record, @Param("example") TSysConfigsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TSysConfigs record, @Param("example") TSysConfigsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TSysConfigs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TSysConfigs record);
}