package com.samchat.common.beans.auto.db.mapper;

import com.samchat.common.beans.auto.db.entitybeans.TUserUsersChangeable;
import com.samchat.common.beans.auto.db.entitybeans.TUserUsersChangeableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserUsersChangeableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    int countByExample(TUserUsersChangeableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    int deleteByExample(TUserUsersChangeableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    int insert(TUserUsersChangeable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    int insertSelective(TUserUsersChangeable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    List<TUserUsersChangeable> selectByExample(TUserUsersChangeableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    TUserUsersChangeable selectByPrimaryKey(Long user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TUserUsersChangeable record, @Param("example") TUserUsersChangeableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TUserUsersChangeable record, @Param("example") TUserUsersChangeableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TUserUsersChangeable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TUserUsersChangeable record);
}