package com.samchat.common.beans.auto.db.entitybeans;

import com.samchat.common.beans.auto.db.BaseEntity;
import java.util.Date;

public class TAdvertisementAdvertisements extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement_advertisements.ads_id
     *
     * @mbggenerated
     */
    private Long ads_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement_advertisements.user_id
     *
     * @mbggenerated
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement_advertisements.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement_advertisements.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement_advertisements.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement_advertisements.create_date
     *
     * @mbggenerated
     */
    private Date create_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement_advertisements.state_date
     *
     * @mbggenerated
     */
    private Date state_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement_advertisements.ads_id
     *
     * @return the value of t_advertisement_advertisements.ads_id
     *
     * @mbggenerated
     */
    public Long getAds_id() {
        return ads_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement_advertisements.ads_id
     *
     * @param ads_id the value for t_advertisement_advertisements.ads_id
     *
     * @mbggenerated
     */
    public void setAds_id(Long ads_id) {
        this.ads_id = ads_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement_advertisements.user_id
     *
     * @return the value of t_advertisement_advertisements.user_id
     *
     * @mbggenerated
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement_advertisements.user_id
     *
     * @param user_id the value for t_advertisement_advertisements.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement_advertisements.type
     *
     * @return the value of t_advertisement_advertisements.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement_advertisements.type
     *
     * @param type the value for t_advertisement_advertisements.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement_advertisements.content
     *
     * @return the value of t_advertisement_advertisements.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement_advertisements.content
     *
     * @param content the value for t_advertisement_advertisements.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement_advertisements.state
     *
     * @return the value of t_advertisement_advertisements.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement_advertisements.state
     *
     * @param state the value for t_advertisement_advertisements.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement_advertisements.create_date
     *
     * @return the value of t_advertisement_advertisements.create_date
     *
     * @mbggenerated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement_advertisements.create_date
     *
     * @param create_date the value for t_advertisement_advertisements.create_date
     *
     * @mbggenerated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement_advertisements.state_date
     *
     * @return the value of t_advertisement_advertisements.state_date
     *
     * @mbggenerated
     */
    public Date getState_date() {
        return state_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement_advertisements.state_date
     *
     * @param state_date the value for t_advertisement_advertisements.state_date
     *
     * @mbggenerated
     */
    public void setState_date(Date state_date) {
        this.state_date = state_date;
    }
}