package com.samchat.common.beans.auto.db.entitybeans;

import com.samchat.common.beans.auto.db.BaseEntity;
import java.util.Date;

public class TContactUser extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contact_user.contact_id
     *
     * @mbggenerated
     */
    private Long contact_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contact_user.user_id
     *
     * @mbggenerated
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contact_user.user_id_pro
     *
     * @mbggenerated
     */
    private Long user_id_pro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contact_user.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contact_user.state_date
     *
     * @mbggenerated
     */
    private Date state_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contact_user.contact_id
     *
     * @return the value of t_contact_user.contact_id
     *
     * @mbggenerated
     */
    public Long getContact_id() {
        return contact_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contact_user.contact_id
     *
     * @param contact_id the value for t_contact_user.contact_id
     *
     * @mbggenerated
     */
    public void setContact_id(Long contact_id) {
        this.contact_id = contact_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contact_user.user_id
     *
     * @return the value of t_contact_user.user_id
     *
     * @mbggenerated
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contact_user.user_id
     *
     * @param user_id the value for t_contact_user.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contact_user.user_id_pro
     *
     * @return the value of t_contact_user.user_id_pro
     *
     * @mbggenerated
     */
    public Long getUser_id_pro() {
        return user_id_pro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contact_user.user_id_pro
     *
     * @param user_id_pro the value for t_contact_user.user_id_pro
     *
     * @mbggenerated
     */
    public void setUser_id_pro(Long user_id_pro) {
        this.user_id_pro = user_id_pro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contact_user.state
     *
     * @return the value of t_contact_user.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contact_user.state
     *
     * @param state the value for t_contact_user.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contact_user.state_date
     *
     * @return the value of t_contact_user.state_date
     *
     * @mbggenerated
     */
    public Date getState_date() {
        return state_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contact_user.state_date
     *
     * @param state_date the value for t_contact_user.state_date
     *
     * @mbggenerated
     */
    public void setState_date(Date state_date) {
        this.state_date = state_date;
    }
}