package com.samchat.common.beans.auto.db.entitybeans;

import com.samchat.common.beans.auto.db.BaseEntity;
import java.util.Date;

public class TQuestionQuestions extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_questions.question_id
     *
     * @mbggenerated
     */
    private Long question_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_questions.opt_type
     *
     * @mbggenerated
     */
    private Byte opt_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_questions.user_id
     *
     * @mbggenerated
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_questions.longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_questions.latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_questions.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_questions.place_id
     *
     * @mbggenerated
     */
    private String place_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_questions.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_questions.create_date
     *
     * @mbggenerated
     */
    private Date create_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_questions.question_id
     *
     * @return the value of t_question_questions.question_id
     *
     * @mbggenerated
     */
    public Long getQuestion_id() {
        return question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_questions.question_id
     *
     * @param question_id the value for t_question_questions.question_id
     *
     * @mbggenerated
     */
    public void setQuestion_id(Long question_id) {
        this.question_id = question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_questions.opt_type
     *
     * @return the value of t_question_questions.opt_type
     *
     * @mbggenerated
     */
    public Byte getOpt_type() {
        return opt_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_questions.opt_type
     *
     * @param opt_type the value for t_question_questions.opt_type
     *
     * @mbggenerated
     */
    public void setOpt_type(Byte opt_type) {
        this.opt_type = opt_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_questions.user_id
     *
     * @return the value of t_question_questions.user_id
     *
     * @mbggenerated
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_questions.user_id
     *
     * @param user_id the value for t_question_questions.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_questions.longitude
     *
     * @return the value of t_question_questions.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_questions.longitude
     *
     * @param longitude the value for t_question_questions.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_questions.latitude
     *
     * @return the value of t_question_questions.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_questions.latitude
     *
     * @param latitude the value for t_question_questions.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_questions.address
     *
     * @return the value of t_question_questions.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_questions.address
     *
     * @param address the value for t_question_questions.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_questions.place_id
     *
     * @return the value of t_question_questions.place_id
     *
     * @mbggenerated
     */
    public String getPlace_id() {
        return place_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_questions.place_id
     *
     * @param place_id the value for t_question_questions.place_id
     *
     * @mbggenerated
     */
    public void setPlace_id(String place_id) {
        this.place_id = place_id == null ? null : place_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_questions.content
     *
     * @return the value of t_question_questions.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_questions.content
     *
     * @param content the value for t_question_questions.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_questions.create_date
     *
     * @return the value of t_question_questions.create_date
     *
     * @mbggenerated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_questions.create_date
     *
     * @param create_date the value for t_question_questions.create_date
     *
     * @mbggenerated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }
}