package com.samchat.common.beans.auto.db.entitybeans;

import com.samchat.common.beans.auto.db.BaseEntity;
import java.util.Date;

public class TQuestionSendLog extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_send_log.qst_log_id
     *
     * @mbggenerated
     */
    private Long qst_log_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_send_log.qst_id
     *
     * @mbggenerated
     */
    private Long qst_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_send_log.user_id_pro
     *
     * @mbggenerated
     */
    private Long user_id_pro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_send_log.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_send_log.state_date
     *
     * @mbggenerated
     */
    private Date state_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_send_log.create_date
     *
     * @mbggenerated
     */
    private Date create_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_send_log.sharding_flag
     *
     * @mbggenerated
     */
    private Integer sharding_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_send_log.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_send_log.qst_log_id
     *
     * @return the value of t_question_send_log.qst_log_id
     *
     * @mbggenerated
     */
    public Long getQst_log_id() {
        return qst_log_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_send_log.qst_log_id
     *
     * @param qst_log_id the value for t_question_send_log.qst_log_id
     *
     * @mbggenerated
     */
    public void setQst_log_id(Long qst_log_id) {
        this.qst_log_id = qst_log_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_send_log.qst_id
     *
     * @return the value of t_question_send_log.qst_id
     *
     * @mbggenerated
     */
    public Long getQst_id() {
        return qst_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_send_log.qst_id
     *
     * @param qst_id the value for t_question_send_log.qst_id
     *
     * @mbggenerated
     */
    public void setQst_id(Long qst_id) {
        this.qst_id = qst_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_send_log.user_id_pro
     *
     * @return the value of t_question_send_log.user_id_pro
     *
     * @mbggenerated
     */
    public Long getUser_id_pro() {
        return user_id_pro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_send_log.user_id_pro
     *
     * @param user_id_pro the value for t_question_send_log.user_id_pro
     *
     * @mbggenerated
     */
    public void setUser_id_pro(Long user_id_pro) {
        this.user_id_pro = user_id_pro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_send_log.state
     *
     * @return the value of t_question_send_log.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_send_log.state
     *
     * @param state the value for t_question_send_log.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_send_log.state_date
     *
     * @return the value of t_question_send_log.state_date
     *
     * @mbggenerated
     */
    public Date getState_date() {
        return state_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_send_log.state_date
     *
     * @param state_date the value for t_question_send_log.state_date
     *
     * @mbggenerated
     */
    public void setState_date(Date state_date) {
        this.state_date = state_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_send_log.create_date
     *
     * @return the value of t_question_send_log.create_date
     *
     * @mbggenerated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_send_log.create_date
     *
     * @param create_date the value for t_question_send_log.create_date
     *
     * @mbggenerated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_send_log.sharding_flag
     *
     * @return the value of t_question_send_log.sharding_flag
     *
     * @mbggenerated
     */
    public Integer getSharding_flag() {
        return sharding_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_send_log.sharding_flag
     *
     * @param sharding_flag the value for t_question_send_log.sharding_flag
     *
     * @mbggenerated
     */
    public void setSharding_flag(Integer sharding_flag) {
        this.sharding_flag = sharding_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_send_log.remark
     *
     * @return the value of t_question_send_log.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_send_log.remark
     *
     * @param remark the value for t_question_send_log.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}