package com.samchat.common.beans.auto.db.entitybeans;

import com.samchat.common.beans.auto.db.BaseEntity;
import java.util.Date;

public class TSysDictInfo extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_dict_info.dict_id
     *
     * @mbggenerated
     */
    private Integer dict_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_dict_info.dict_group
     *
     * @mbggenerated
     */
    private String dict_group;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_dict_info.dict_code
     *
     * @mbggenerated
     */
    private String dict_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_dict_info.dict_name
     *
     * @mbggenerated
     */
    private String dict_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_dict_info.dict_desc
     *
     * @mbggenerated
     */
    private String dict_desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_dict_info.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_dict_info.state_date
     *
     * @mbggenerated
     */
    private Date state_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_dict_info.dict_id
     *
     * @return the value of t_sys_dict_info.dict_id
     *
     * @mbggenerated
     */
    public Integer getDict_id() {
        return dict_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_dict_info.dict_id
     *
     * @param dict_id the value for t_sys_dict_info.dict_id
     *
     * @mbggenerated
     */
    public void setDict_id(Integer dict_id) {
        this.dict_id = dict_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_dict_info.dict_group
     *
     * @return the value of t_sys_dict_info.dict_group
     *
     * @mbggenerated
     */
    public String getDict_group() {
        return dict_group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_dict_info.dict_group
     *
     * @param dict_group the value for t_sys_dict_info.dict_group
     *
     * @mbggenerated
     */
    public void setDict_group(String dict_group) {
        this.dict_group = dict_group == null ? null : dict_group.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_dict_info.dict_code
     *
     * @return the value of t_sys_dict_info.dict_code
     *
     * @mbggenerated
     */
    public String getDict_code() {
        return dict_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_dict_info.dict_code
     *
     * @param dict_code the value for t_sys_dict_info.dict_code
     *
     * @mbggenerated
     */
    public void setDict_code(String dict_code) {
        this.dict_code = dict_code == null ? null : dict_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_dict_info.dict_name
     *
     * @return the value of t_sys_dict_info.dict_name
     *
     * @mbggenerated
     */
    public String getDict_name() {
        return dict_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_dict_info.dict_name
     *
     * @param dict_name the value for t_sys_dict_info.dict_name
     *
     * @mbggenerated
     */
    public void setDict_name(String dict_name) {
        this.dict_name = dict_name == null ? null : dict_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_dict_info.dict_desc
     *
     * @return the value of t_sys_dict_info.dict_desc
     *
     * @mbggenerated
     */
    public String getDict_desc() {
        return dict_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_dict_info.dict_desc
     *
     * @param dict_desc the value for t_sys_dict_info.dict_desc
     *
     * @mbggenerated
     */
    public void setDict_desc(String dict_desc) {
        this.dict_desc = dict_desc == null ? null : dict_desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_dict_info.state
     *
     * @return the value of t_sys_dict_info.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_dict_info.state
     *
     * @param state the value for t_sys_dict_info.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_dict_info.state_date
     *
     * @return the value of t_sys_dict_info.state_date
     *
     * @mbggenerated
     */
    public Date getState_date() {
        return state_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_dict_info.state_date
     *
     * @param state_date the value for t_sys_dict_info.state_date
     *
     * @mbggenerated
     */
    public void setState_date(Date state_date) {
        this.state_date = state_date;
    }
}