package com.samchat.common.beans.auto.db.entitybeans;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TSysDictInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated
     */
    public TSysDictInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDict_idIsNull() {
            addCriterion("dict_id is null");
            return (Criteria) this;
        }

        public Criteria andDict_idIsNotNull() {
            addCriterion("dict_id is not null");
            return (Criteria) this;
        }

        public Criteria andDict_idEqualTo(Integer value) {
            addCriterion("dict_id =", value, "dict_id");
            return (Criteria) this;
        }

        public Criteria andDict_idNotEqualTo(Integer value) {
            addCriterion("dict_id <>", value, "dict_id");
            return (Criteria) this;
        }

        public Criteria andDict_idGreaterThan(Integer value) {
            addCriterion("dict_id >", value, "dict_id");
            return (Criteria) this;
        }

        public Criteria andDict_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("dict_id >=", value, "dict_id");
            return (Criteria) this;
        }

        public Criteria andDict_idLessThan(Integer value) {
            addCriterion("dict_id <", value, "dict_id");
            return (Criteria) this;
        }

        public Criteria andDict_idLessThanOrEqualTo(Integer value) {
            addCriterion("dict_id <=", value, "dict_id");
            return (Criteria) this;
        }

        public Criteria andDict_idIn(List<Integer> values) {
            addCriterion("dict_id in", values, "dict_id");
            return (Criteria) this;
        }

        public Criteria andDict_idNotIn(List<Integer> values) {
            addCriterion("dict_id not in", values, "dict_id");
            return (Criteria) this;
        }

        public Criteria andDict_idBetween(Integer value1, Integer value2) {
            addCriterion("dict_id between", value1, value2, "dict_id");
            return (Criteria) this;
        }

        public Criteria andDict_idNotBetween(Integer value1, Integer value2) {
            addCriterion("dict_id not between", value1, value2, "dict_id");
            return (Criteria) this;
        }

        public Criteria andDict_groupIsNull() {
            addCriterion("dict_group is null");
            return (Criteria) this;
        }

        public Criteria andDict_groupIsNotNull() {
            addCriterion("dict_group is not null");
            return (Criteria) this;
        }

        public Criteria andDict_groupEqualTo(String value) {
            addCriterion("dict_group =", value, "dict_group");
            return (Criteria) this;
        }

        public Criteria andDict_groupNotEqualTo(String value) {
            addCriterion("dict_group <>", value, "dict_group");
            return (Criteria) this;
        }

        public Criteria andDict_groupGreaterThan(String value) {
            addCriterion("dict_group >", value, "dict_group");
            return (Criteria) this;
        }

        public Criteria andDict_groupGreaterThanOrEqualTo(String value) {
            addCriterion("dict_group >=", value, "dict_group");
            return (Criteria) this;
        }

        public Criteria andDict_groupLessThan(String value) {
            addCriterion("dict_group <", value, "dict_group");
            return (Criteria) this;
        }

        public Criteria andDict_groupLessThanOrEqualTo(String value) {
            addCriterion("dict_group <=", value, "dict_group");
            return (Criteria) this;
        }

        public Criteria andDict_groupLike(String value) {
            addCriterion("dict_group like", value, "dict_group");
            return (Criteria) this;
        }

        public Criteria andDict_groupNotLike(String value) {
            addCriterion("dict_group not like", value, "dict_group");
            return (Criteria) this;
        }

        public Criteria andDict_groupIn(List<String> values) {
            addCriterion("dict_group in", values, "dict_group");
            return (Criteria) this;
        }

        public Criteria andDict_groupNotIn(List<String> values) {
            addCriterion("dict_group not in", values, "dict_group");
            return (Criteria) this;
        }

        public Criteria andDict_groupBetween(String value1, String value2) {
            addCriterion("dict_group between", value1, value2, "dict_group");
            return (Criteria) this;
        }

        public Criteria andDict_groupNotBetween(String value1, String value2) {
            addCriterion("dict_group not between", value1, value2, "dict_group");
            return (Criteria) this;
        }

        public Criteria andDict_codeIsNull() {
            addCriterion("dict_code is null");
            return (Criteria) this;
        }

        public Criteria andDict_codeIsNotNull() {
            addCriterion("dict_code is not null");
            return (Criteria) this;
        }

        public Criteria andDict_codeEqualTo(String value) {
            addCriterion("dict_code =", value, "dict_code");
            return (Criteria) this;
        }

        public Criteria andDict_codeNotEqualTo(String value) {
            addCriterion("dict_code <>", value, "dict_code");
            return (Criteria) this;
        }

        public Criteria andDict_codeGreaterThan(String value) {
            addCriterion("dict_code >", value, "dict_code");
            return (Criteria) this;
        }

        public Criteria andDict_codeGreaterThanOrEqualTo(String value) {
            addCriterion("dict_code >=", value, "dict_code");
            return (Criteria) this;
        }

        public Criteria andDict_codeLessThan(String value) {
            addCriterion("dict_code <", value, "dict_code");
            return (Criteria) this;
        }

        public Criteria andDict_codeLessThanOrEqualTo(String value) {
            addCriterion("dict_code <=", value, "dict_code");
            return (Criteria) this;
        }

        public Criteria andDict_codeLike(String value) {
            addCriterion("dict_code like", value, "dict_code");
            return (Criteria) this;
        }

        public Criteria andDict_codeNotLike(String value) {
            addCriterion("dict_code not like", value, "dict_code");
            return (Criteria) this;
        }

        public Criteria andDict_codeIn(List<String> values) {
            addCriterion("dict_code in", values, "dict_code");
            return (Criteria) this;
        }

        public Criteria andDict_codeNotIn(List<String> values) {
            addCriterion("dict_code not in", values, "dict_code");
            return (Criteria) this;
        }

        public Criteria andDict_codeBetween(String value1, String value2) {
            addCriterion("dict_code between", value1, value2, "dict_code");
            return (Criteria) this;
        }

        public Criteria andDict_codeNotBetween(String value1, String value2) {
            addCriterion("dict_code not between", value1, value2, "dict_code");
            return (Criteria) this;
        }

        public Criteria andDict_nameIsNull() {
            addCriterion("dict_name is null");
            return (Criteria) this;
        }

        public Criteria andDict_nameIsNotNull() {
            addCriterion("dict_name is not null");
            return (Criteria) this;
        }

        public Criteria andDict_nameEqualTo(String value) {
            addCriterion("dict_name =", value, "dict_name");
            return (Criteria) this;
        }

        public Criteria andDict_nameNotEqualTo(String value) {
            addCriterion("dict_name <>", value, "dict_name");
            return (Criteria) this;
        }

        public Criteria andDict_nameGreaterThan(String value) {
            addCriterion("dict_name >", value, "dict_name");
            return (Criteria) this;
        }

        public Criteria andDict_nameGreaterThanOrEqualTo(String value) {
            addCriterion("dict_name >=", value, "dict_name");
            return (Criteria) this;
        }

        public Criteria andDict_nameLessThan(String value) {
            addCriterion("dict_name <", value, "dict_name");
            return (Criteria) this;
        }

        public Criteria andDict_nameLessThanOrEqualTo(String value) {
            addCriterion("dict_name <=", value, "dict_name");
            return (Criteria) this;
        }

        public Criteria andDict_nameLike(String value) {
            addCriterion("dict_name like", value, "dict_name");
            return (Criteria) this;
        }

        public Criteria andDict_nameNotLike(String value) {
            addCriterion("dict_name not like", value, "dict_name");
            return (Criteria) this;
        }

        public Criteria andDict_nameIn(List<String> values) {
            addCriterion("dict_name in", values, "dict_name");
            return (Criteria) this;
        }

        public Criteria andDict_nameNotIn(List<String> values) {
            addCriterion("dict_name not in", values, "dict_name");
            return (Criteria) this;
        }

        public Criteria andDict_nameBetween(String value1, String value2) {
            addCriterion("dict_name between", value1, value2, "dict_name");
            return (Criteria) this;
        }

        public Criteria andDict_nameNotBetween(String value1, String value2) {
            addCriterion("dict_name not between", value1, value2, "dict_name");
            return (Criteria) this;
        }

        public Criteria andDict_descIsNull() {
            addCriterion("dict_desc is null");
            return (Criteria) this;
        }

        public Criteria andDict_descIsNotNull() {
            addCriterion("dict_desc is not null");
            return (Criteria) this;
        }

        public Criteria andDict_descEqualTo(String value) {
            addCriterion("dict_desc =", value, "dict_desc");
            return (Criteria) this;
        }

        public Criteria andDict_descNotEqualTo(String value) {
            addCriterion("dict_desc <>", value, "dict_desc");
            return (Criteria) this;
        }

        public Criteria andDict_descGreaterThan(String value) {
            addCriterion("dict_desc >", value, "dict_desc");
            return (Criteria) this;
        }

        public Criteria andDict_descGreaterThanOrEqualTo(String value) {
            addCriterion("dict_desc >=", value, "dict_desc");
            return (Criteria) this;
        }

        public Criteria andDict_descLessThan(String value) {
            addCriterion("dict_desc <", value, "dict_desc");
            return (Criteria) this;
        }

        public Criteria andDict_descLessThanOrEqualTo(String value) {
            addCriterion("dict_desc <=", value, "dict_desc");
            return (Criteria) this;
        }

        public Criteria andDict_descLike(String value) {
            addCriterion("dict_desc like", value, "dict_desc");
            return (Criteria) this;
        }

        public Criteria andDict_descNotLike(String value) {
            addCriterion("dict_desc not like", value, "dict_desc");
            return (Criteria) this;
        }

        public Criteria andDict_descIn(List<String> values) {
            addCriterion("dict_desc in", values, "dict_desc");
            return (Criteria) this;
        }

        public Criteria andDict_descNotIn(List<String> values) {
            addCriterion("dict_desc not in", values, "dict_desc");
            return (Criteria) this;
        }

        public Criteria andDict_descBetween(String value1, String value2) {
            addCriterion("dict_desc between", value1, value2, "dict_desc");
            return (Criteria) this;
        }

        public Criteria andDict_descNotBetween(String value1, String value2) {
            addCriterion("dict_desc not between", value1, value2, "dict_desc");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andState_dateIsNull() {
            addCriterion("state_date is null");
            return (Criteria) this;
        }

        public Criteria andState_dateIsNotNull() {
            addCriterion("state_date is not null");
            return (Criteria) this;
        }

        public Criteria andState_dateEqualTo(Date value) {
            addCriterion("state_date =", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotEqualTo(Date value) {
            addCriterion("state_date <>", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateGreaterThan(Date value) {
            addCriterion("state_date >", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("state_date >=", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateLessThan(Date value) {
            addCriterion("state_date <", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateLessThanOrEqualTo(Date value) {
            addCriterion("state_date <=", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateIn(List<Date> values) {
            addCriterion("state_date in", values, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotIn(List<Date> values) {
            addCriterion("state_date not in", values, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateBetween(Date value1, Date value2) {
            addCriterion("state_date between", value1, value2, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotBetween(Date value1, Date value2) {
            addCriterion("state_date not between", value1, value2, "state_date");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_dict_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}