package com.samchat.common.beans.auto.db.entitybeans;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TSysMessageTempleteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated
     */
    public TSysMessageTempleteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAction_codeIsNull() {
            addCriterion("action_code is null");
            return (Criteria) this;
        }

        public Criteria andAction_codeIsNotNull() {
            addCriterion("action_code is not null");
            return (Criteria) this;
        }

        public Criteria andAction_codeEqualTo(String value) {
            addCriterion("action_code =", value, "action_code");
            return (Criteria) this;
        }

        public Criteria andAction_codeNotEqualTo(String value) {
            addCriterion("action_code <>", value, "action_code");
            return (Criteria) this;
        }

        public Criteria andAction_codeGreaterThan(String value) {
            addCriterion("action_code >", value, "action_code");
            return (Criteria) this;
        }

        public Criteria andAction_codeGreaterThanOrEqualTo(String value) {
            addCriterion("action_code >=", value, "action_code");
            return (Criteria) this;
        }

        public Criteria andAction_codeLessThan(String value) {
            addCriterion("action_code <", value, "action_code");
            return (Criteria) this;
        }

        public Criteria andAction_codeLessThanOrEqualTo(String value) {
            addCriterion("action_code <=", value, "action_code");
            return (Criteria) this;
        }

        public Criteria andAction_codeLike(String value) {
            addCriterion("action_code like", value, "action_code");
            return (Criteria) this;
        }

        public Criteria andAction_codeNotLike(String value) {
            addCriterion("action_code not like", value, "action_code");
            return (Criteria) this;
        }

        public Criteria andAction_codeIn(List<String> values) {
            addCriterion("action_code in", values, "action_code");
            return (Criteria) this;
        }

        public Criteria andAction_codeNotIn(List<String> values) {
            addCriterion("action_code not in", values, "action_code");
            return (Criteria) this;
        }

        public Criteria andAction_codeBetween(String value1, String value2) {
            addCriterion("action_code between", value1, value2, "action_code");
            return (Criteria) this;
        }

        public Criteria andAction_codeNotBetween(String value1, String value2) {
            addCriterion("action_code not between", value1, value2, "action_code");
            return (Criteria) this;
        }

        public Criteria andAction_typeIsNull() {
            addCriterion("action_type is null");
            return (Criteria) this;
        }

        public Criteria andAction_typeIsNotNull() {
            addCriterion("action_type is not null");
            return (Criteria) this;
        }

        public Criteria andAction_typeEqualTo(Short value) {
            addCriterion("action_type =", value, "action_type");
            return (Criteria) this;
        }

        public Criteria andAction_typeNotEqualTo(Short value) {
            addCriterion("action_type <>", value, "action_type");
            return (Criteria) this;
        }

        public Criteria andAction_typeGreaterThan(Short value) {
            addCriterion("action_type >", value, "action_type");
            return (Criteria) this;
        }

        public Criteria andAction_typeGreaterThanOrEqualTo(Short value) {
            addCriterion("action_type >=", value, "action_type");
            return (Criteria) this;
        }

        public Criteria andAction_typeLessThan(Short value) {
            addCriterion("action_type <", value, "action_type");
            return (Criteria) this;
        }

        public Criteria andAction_typeLessThanOrEqualTo(Short value) {
            addCriterion("action_type <=", value, "action_type");
            return (Criteria) this;
        }

        public Criteria andAction_typeIn(List<Short> values) {
            addCriterion("action_type in", values, "action_type");
            return (Criteria) this;
        }

        public Criteria andAction_typeNotIn(List<Short> values) {
            addCriterion("action_type not in", values, "action_type");
            return (Criteria) this;
        }

        public Criteria andAction_typeBetween(Short value1, Short value2) {
            addCriterion("action_type between", value1, value2, "action_type");
            return (Criteria) this;
        }

        public Criteria andAction_typeNotBetween(Short value1, Short value2) {
            addCriterion("action_type not between", value1, value2, "action_type");
            return (Criteria) this;
        }

        public Criteria andTempleteIsNull() {
            addCriterion("templete is null");
            return (Criteria) this;
        }

        public Criteria andTempleteIsNotNull() {
            addCriterion("templete is not null");
            return (Criteria) this;
        }

        public Criteria andTempleteEqualTo(String value) {
            addCriterion("templete =", value, "templete");
            return (Criteria) this;
        }

        public Criteria andTempleteNotEqualTo(String value) {
            addCriterion("templete <>", value, "templete");
            return (Criteria) this;
        }

        public Criteria andTempleteGreaterThan(String value) {
            addCriterion("templete >", value, "templete");
            return (Criteria) this;
        }

        public Criteria andTempleteGreaterThanOrEqualTo(String value) {
            addCriterion("templete >=", value, "templete");
            return (Criteria) this;
        }

        public Criteria andTempleteLessThan(String value) {
            addCriterion("templete <", value, "templete");
            return (Criteria) this;
        }

        public Criteria andTempleteLessThanOrEqualTo(String value) {
            addCriterion("templete <=", value, "templete");
            return (Criteria) this;
        }

        public Criteria andTempleteLike(String value) {
            addCriterion("templete like", value, "templete");
            return (Criteria) this;
        }

        public Criteria andTempleteNotLike(String value) {
            addCriterion("templete not like", value, "templete");
            return (Criteria) this;
        }

        public Criteria andTempleteIn(List<String> values) {
            addCriterion("templete in", values, "templete");
            return (Criteria) this;
        }

        public Criteria andTempleteNotIn(List<String> values) {
            addCriterion("templete not in", values, "templete");
            return (Criteria) this;
        }

        public Criteria andTempleteBetween(String value1, String value2) {
            addCriterion("templete between", value1, value2, "templete");
            return (Criteria) this;
        }

        public Criteria andTempleteNotBetween(String value1, String value2) {
            addCriterion("templete not between", value1, value2, "templete");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Byte value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Byte value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Byte value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Byte value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Byte value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Byte> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Byte> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Byte value1, Byte value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Byte value1, Byte value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andState_dateIsNull() {
            addCriterion("state_date is null");
            return (Criteria) this;
        }

        public Criteria andState_dateIsNotNull() {
            addCriterion("state_date is not null");
            return (Criteria) this;
        }

        public Criteria andState_dateEqualTo(Date value) {
            addCriterion("state_date =", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotEqualTo(Date value) {
            addCriterion("state_date <>", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateGreaterThan(Date value) {
            addCriterion("state_date >", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("state_date >=", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateLessThan(Date value) {
            addCriterion("state_date <", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateLessThanOrEqualTo(Date value) {
            addCriterion("state_date <=", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateIn(List<Date> values) {
            addCriterion("state_date in", values, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotIn(List<Date> values) {
            addCriterion("state_date not in", values, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateBetween(Date value1, Date value2) {
            addCriterion("state_date between", value1, value2, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotBetween(Date value1, Date value2) {
            addCriterion("state_date not between", value1, value2, "state_date");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_message_templete
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}