package com.samchat.common.beans.auto.db.entitybeans;

import com.samchat.common.beans.auto.db.BaseEntity;
import java.util.Date;

public class TUserUsersChangeable extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_users_changeable.user_id
     *
     * @mbggenerated
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_users_changeable.client_id
     *
     * @mbggenerated
     */
    private String client_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_users_changeable.device_id
     *
     * @mbggenerated
     */
    private String device_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_users_changeable.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_users_changeable.servicer_list_state_date
     *
     * @mbggenerated
     */
    private Date servicer_list_state_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_users_changeable.customer_list_state_date
     *
     * @mbggenerated
     */
    private Date customer_list_state_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_users_changeable.follow_list_state_date
     *
     * @mbggenerated
     */
    private Date follow_list_state_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_users_changeable.state_date
     *
     * @mbggenerated
     */
    private Date state_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_users_changeable.user_id
     *
     * @return the value of t_user_users_changeable.user_id
     *
     * @mbggenerated
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_users_changeable.user_id
     *
     * @param user_id the value for t_user_users_changeable.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_users_changeable.client_id
     *
     * @return the value of t_user_users_changeable.client_id
     *
     * @mbggenerated
     */
    public String getClient_id() {
        return client_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_users_changeable.client_id
     *
     * @param client_id the value for t_user_users_changeable.client_id
     *
     * @mbggenerated
     */
    public void setClient_id(String client_id) {
        this.client_id = client_id == null ? null : client_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_users_changeable.device_id
     *
     * @return the value of t_user_users_changeable.device_id
     *
     * @mbggenerated
     */
    public String getDevice_id() {
        return device_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_users_changeable.device_id
     *
     * @param device_id the value for t_user_users_changeable.device_id
     *
     * @mbggenerated
     */
    public void setDevice_id(String device_id) {
        this.device_id = device_id == null ? null : device_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_users_changeable.token
     *
     * @return the value of t_user_users_changeable.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_users_changeable.token
     *
     * @param token the value for t_user_users_changeable.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_users_changeable.servicer_list_state_date
     *
     * @return the value of t_user_users_changeable.servicer_list_state_date
     *
     * @mbggenerated
     */
    public Date getServicer_list_state_date() {
        return servicer_list_state_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_users_changeable.servicer_list_state_date
     *
     * @param servicer_list_state_date the value for t_user_users_changeable.servicer_list_state_date
     *
     * @mbggenerated
     */
    public void setServicer_list_state_date(Date servicer_list_state_date) {
        this.servicer_list_state_date = servicer_list_state_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_users_changeable.customer_list_state_date
     *
     * @return the value of t_user_users_changeable.customer_list_state_date
     *
     * @mbggenerated
     */
    public Date getCustomer_list_state_date() {
        return customer_list_state_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_users_changeable.customer_list_state_date
     *
     * @param customer_list_state_date the value for t_user_users_changeable.customer_list_state_date
     *
     * @mbggenerated
     */
    public void setCustomer_list_state_date(Date customer_list_state_date) {
        this.customer_list_state_date = customer_list_state_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_users_changeable.follow_list_state_date
     *
     * @return the value of t_user_users_changeable.follow_list_state_date
     *
     * @mbggenerated
     */
    public Date getFollow_list_state_date() {
        return follow_list_state_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_users_changeable.follow_list_state_date
     *
     * @param follow_list_state_date the value for t_user_users_changeable.follow_list_state_date
     *
     * @mbggenerated
     */
    public void setFollow_list_state_date(Date follow_list_state_date) {
        this.follow_list_state_date = follow_list_state_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_users_changeable.state_date
     *
     * @return the value of t_user_users_changeable.state_date
     *
     * @mbggenerated
     */
    public Date getState_date() {
        return state_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_users_changeable.state_date
     *
     * @param state_date the value for t_user_users_changeable.state_date
     *
     * @mbggenerated
     */
    public void setState_date(Date state_date) {
        this.state_date = state_date;
    }
}