package com.samchat.common.beans.auto.db.entitybeans;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TUserUsersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    public TUserUsersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUser_idIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser_idEqualTo(Long value) {
            addCriterion("user_id =", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThan(Long value) {
            addCriterion("user_id >", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThan(Long value) {
            addCriterion("user_id <", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIn(List<Long> values) {
            addCriterion("user_id in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_typeIsNull() {
            addCriterion("user_type is null");
            return (Criteria) this;
        }

        public Criteria andUser_typeIsNotNull() {
            addCriterion("user_type is not null");
            return (Criteria) this;
        }

        public Criteria andUser_typeEqualTo(Byte value) {
            addCriterion("user_type =", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeNotEqualTo(Byte value) {
            addCriterion("user_type <>", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeGreaterThan(Byte value) {
            addCriterion("user_type >", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeGreaterThanOrEqualTo(Byte value) {
            addCriterion("user_type >=", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeLessThan(Byte value) {
            addCriterion("user_type <", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeLessThanOrEqualTo(Byte value) {
            addCriterion("user_type <=", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeIn(List<Byte> values) {
            addCriterion("user_type in", values, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeNotIn(List<Byte> values) {
            addCriterion("user_type not in", values, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeBetween(Byte value1, Byte value2) {
            addCriterion("user_type between", value1, value2, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeNotBetween(Byte value1, Byte value2) {
            addCriterion("user_type not between", value1, value2, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_nameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUser_nameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUser_nameEqualTo(String value) {
            addCriterion("user_name =", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameGreaterThan(String value) {
            addCriterion("user_name >", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameLessThan(String value) {
            addCriterion("user_name <", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameLike(String value) {
            addCriterion("user_name like", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameNotLike(String value) {
            addCriterion("user_name not like", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameIn(List<String> values) {
            addCriterion("user_name in", values, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_pwdIsNull() {
            addCriterion("user_pwd is null");
            return (Criteria) this;
        }

        public Criteria andUser_pwdIsNotNull() {
            addCriterion("user_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andUser_pwdEqualTo(String value) {
            addCriterion("user_pwd =", value, "user_pwd");
            return (Criteria) this;
        }

        public Criteria andUser_pwdNotEqualTo(String value) {
            addCriterion("user_pwd <>", value, "user_pwd");
            return (Criteria) this;
        }

        public Criteria andUser_pwdGreaterThan(String value) {
            addCriterion("user_pwd >", value, "user_pwd");
            return (Criteria) this;
        }

        public Criteria andUser_pwdGreaterThanOrEqualTo(String value) {
            addCriterion("user_pwd >=", value, "user_pwd");
            return (Criteria) this;
        }

        public Criteria andUser_pwdLessThan(String value) {
            addCriterion("user_pwd <", value, "user_pwd");
            return (Criteria) this;
        }

        public Criteria andUser_pwdLessThanOrEqualTo(String value) {
            addCriterion("user_pwd <=", value, "user_pwd");
            return (Criteria) this;
        }

        public Criteria andUser_pwdLike(String value) {
            addCriterion("user_pwd like", value, "user_pwd");
            return (Criteria) this;
        }

        public Criteria andUser_pwdNotLike(String value) {
            addCriterion("user_pwd not like", value, "user_pwd");
            return (Criteria) this;
        }

        public Criteria andUser_pwdIn(List<String> values) {
            addCriterion("user_pwd in", values, "user_pwd");
            return (Criteria) this;
        }

        public Criteria andUser_pwdNotIn(List<String> values) {
            addCriterion("user_pwd not in", values, "user_pwd");
            return (Criteria) this;
        }

        public Criteria andUser_pwdBetween(String value1, String value2) {
            addCriterion("user_pwd between", value1, value2, "user_pwd");
            return (Criteria) this;
        }

        public Criteria andUser_pwdNotBetween(String value1, String value2) {
            addCriterion("user_pwd not between", value1, value2, "user_pwd");
            return (Criteria) this;
        }

        public Criteria andCountry_codeIsNull() {
            addCriterion("country_code is null");
            return (Criteria) this;
        }

        public Criteria andCountry_codeIsNotNull() {
            addCriterion("country_code is not null");
            return (Criteria) this;
        }

        public Criteria andCountry_codeEqualTo(String value) {
            addCriterion("country_code =", value, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeNotEqualTo(String value) {
            addCriterion("country_code <>", value, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeGreaterThan(String value) {
            addCriterion("country_code >", value, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeGreaterThanOrEqualTo(String value) {
            addCriterion("country_code >=", value, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeLessThan(String value) {
            addCriterion("country_code <", value, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeLessThanOrEqualTo(String value) {
            addCriterion("country_code <=", value, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeLike(String value) {
            addCriterion("country_code like", value, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeNotLike(String value) {
            addCriterion("country_code not like", value, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeIn(List<String> values) {
            addCriterion("country_code in", values, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeNotIn(List<String> values) {
            addCriterion("country_code not in", values, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeBetween(String value1, String value2) {
            addCriterion("country_code between", value1, value2, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeNotBetween(String value1, String value2) {
            addCriterion("country_code not between", value1, value2, "country_code");
            return (Criteria) this;
        }

        public Criteria andPhone_noIsNull() {
            addCriterion("phone_no is null");
            return (Criteria) this;
        }

        public Criteria andPhone_noIsNotNull() {
            addCriterion("phone_no is not null");
            return (Criteria) this;
        }

        public Criteria andPhone_noEqualTo(String value) {
            addCriterion("phone_no =", value, "phone_no");
            return (Criteria) this;
        }

        public Criteria andPhone_noNotEqualTo(String value) {
            addCriterion("phone_no <>", value, "phone_no");
            return (Criteria) this;
        }

        public Criteria andPhone_noGreaterThan(String value) {
            addCriterion("phone_no >", value, "phone_no");
            return (Criteria) this;
        }

        public Criteria andPhone_noGreaterThanOrEqualTo(String value) {
            addCriterion("phone_no >=", value, "phone_no");
            return (Criteria) this;
        }

        public Criteria andPhone_noLessThan(String value) {
            addCriterion("phone_no <", value, "phone_no");
            return (Criteria) this;
        }

        public Criteria andPhone_noLessThanOrEqualTo(String value) {
            addCriterion("phone_no <=", value, "phone_no");
            return (Criteria) this;
        }

        public Criteria andPhone_noLike(String value) {
            addCriterion("phone_no like", value, "phone_no");
            return (Criteria) this;
        }

        public Criteria andPhone_noNotLike(String value) {
            addCriterion("phone_no not like", value, "phone_no");
            return (Criteria) this;
        }

        public Criteria andPhone_noIn(List<String> values) {
            addCriterion("phone_no in", values, "phone_no");
            return (Criteria) this;
        }

        public Criteria andPhone_noNotIn(List<String> values) {
            addCriterion("phone_no not in", values, "phone_no");
            return (Criteria) this;
        }

        public Criteria andPhone_noBetween(String value1, String value2) {
            addCriterion("phone_no between", value1, value2, "phone_no");
            return (Criteria) this;
        }

        public Criteria andPhone_noNotBetween(String value1, String value2) {
            addCriterion("phone_no not between", value1, value2, "phone_no");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAvatar_originIsNull() {
            addCriterion("avatar_origin is null");
            return (Criteria) this;
        }

        public Criteria andAvatar_originIsNotNull() {
            addCriterion("avatar_origin is not null");
            return (Criteria) this;
        }

        public Criteria andAvatar_originEqualTo(String value) {
            addCriterion("avatar_origin =", value, "avatar_origin");
            return (Criteria) this;
        }

        public Criteria andAvatar_originNotEqualTo(String value) {
            addCriterion("avatar_origin <>", value, "avatar_origin");
            return (Criteria) this;
        }

        public Criteria andAvatar_originGreaterThan(String value) {
            addCriterion("avatar_origin >", value, "avatar_origin");
            return (Criteria) this;
        }

        public Criteria andAvatar_originGreaterThanOrEqualTo(String value) {
            addCriterion("avatar_origin >=", value, "avatar_origin");
            return (Criteria) this;
        }

        public Criteria andAvatar_originLessThan(String value) {
            addCriterion("avatar_origin <", value, "avatar_origin");
            return (Criteria) this;
        }

        public Criteria andAvatar_originLessThanOrEqualTo(String value) {
            addCriterion("avatar_origin <=", value, "avatar_origin");
            return (Criteria) this;
        }

        public Criteria andAvatar_originLike(String value) {
            addCriterion("avatar_origin like", value, "avatar_origin");
            return (Criteria) this;
        }

        public Criteria andAvatar_originNotLike(String value) {
            addCriterion("avatar_origin not like", value, "avatar_origin");
            return (Criteria) this;
        }

        public Criteria andAvatar_originIn(List<String> values) {
            addCriterion("avatar_origin in", values, "avatar_origin");
            return (Criteria) this;
        }

        public Criteria andAvatar_originNotIn(List<String> values) {
            addCriterion("avatar_origin not in", values, "avatar_origin");
            return (Criteria) this;
        }

        public Criteria andAvatar_originBetween(String value1, String value2) {
            addCriterion("avatar_origin between", value1, value2, "avatar_origin");
            return (Criteria) this;
        }

        public Criteria andAvatar_originNotBetween(String value1, String value2) {
            addCriterion("avatar_origin not between", value1, value2, "avatar_origin");
            return (Criteria) this;
        }

        public Criteria andAvatar_thumbIsNull() {
            addCriterion("avatar_thumb is null");
            return (Criteria) this;
        }

        public Criteria andAvatar_thumbIsNotNull() {
            addCriterion("avatar_thumb is not null");
            return (Criteria) this;
        }

        public Criteria andAvatar_thumbEqualTo(String value) {
            addCriterion("avatar_thumb =", value, "avatar_thumb");
            return (Criteria) this;
        }

        public Criteria andAvatar_thumbNotEqualTo(String value) {
            addCriterion("avatar_thumb <>", value, "avatar_thumb");
            return (Criteria) this;
        }

        public Criteria andAvatar_thumbGreaterThan(String value) {
            addCriterion("avatar_thumb >", value, "avatar_thumb");
            return (Criteria) this;
        }

        public Criteria andAvatar_thumbGreaterThanOrEqualTo(String value) {
            addCriterion("avatar_thumb >=", value, "avatar_thumb");
            return (Criteria) this;
        }

        public Criteria andAvatar_thumbLessThan(String value) {
            addCriterion("avatar_thumb <", value, "avatar_thumb");
            return (Criteria) this;
        }

        public Criteria andAvatar_thumbLessThanOrEqualTo(String value) {
            addCriterion("avatar_thumb <=", value, "avatar_thumb");
            return (Criteria) this;
        }

        public Criteria andAvatar_thumbLike(String value) {
            addCriterion("avatar_thumb like", value, "avatar_thumb");
            return (Criteria) this;
        }

        public Criteria andAvatar_thumbNotLike(String value) {
            addCriterion("avatar_thumb not like", value, "avatar_thumb");
            return (Criteria) this;
        }

        public Criteria andAvatar_thumbIn(List<String> values) {
            addCriterion("avatar_thumb in", values, "avatar_thumb");
            return (Criteria) this;
        }

        public Criteria andAvatar_thumbNotIn(List<String> values) {
            addCriterion("avatar_thumb not in", values, "avatar_thumb");
            return (Criteria) this;
        }

        public Criteria andAvatar_thumbBetween(String value1, String value2) {
            addCriterion("avatar_thumb between", value1, value2, "avatar_thumb");
            return (Criteria) this;
        }

        public Criteria andAvatar_thumbNotBetween(String value1, String value2) {
            addCriterion("avatar_thumb not between", value1, value2, "avatar_thumb");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Byte value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Byte value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Byte value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Byte value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Byte value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Byte> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Byte> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Byte value1, Byte value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Byte value1, Byte value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andState_dateIsNull() {
            addCriterion("state_date is null");
            return (Criteria) this;
        }

        public Criteria andState_dateIsNotNull() {
            addCriterion("state_date is not null");
            return (Criteria) this;
        }

        public Criteria andState_dateEqualTo(Date value) {
            addCriterion("state_date =", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotEqualTo(Date value) {
            addCriterion("state_date <>", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateGreaterThan(Date value) {
            addCriterion("state_date >", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("state_date >=", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateLessThan(Date value) {
            addCriterion("state_date <", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateLessThanOrEqualTo(Date value) {
            addCriterion("state_date <=", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateIn(List<Date> values) {
            addCriterion("state_date in", values, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotIn(List<Date> values) {
            addCriterion("state_date not in", values, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateBetween(Date value1, Date value2) {
            addCriterion("state_date between", value1, value2, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotBetween(Date value1, Date value2) {
            addCriterion("state_date not between", value1, value2, "state_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreate_dateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_dateEqualTo(Date value) {
            addCriterion("create_date =", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateGreaterThan(Date value) {
            addCriterion("create_date >", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateLessThan(Date value) {
            addCriterion("create_date <", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateIn(List<Date> values) {
            addCriterion("create_date in", values, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "create_date");
            return (Criteria) this;
        }

        public Criteria andCur_tokenIsNull() {
            addCriterion("cur_token is null");
            return (Criteria) this;
        }

        public Criteria andCur_tokenIsNotNull() {
            addCriterion("cur_token is not null");
            return (Criteria) this;
        }

        public Criteria andCur_tokenEqualTo(String value) {
            addCriterion("cur_token =", value, "cur_token");
            return (Criteria) this;
        }

        public Criteria andCur_tokenNotEqualTo(String value) {
            addCriterion("cur_token <>", value, "cur_token");
            return (Criteria) this;
        }

        public Criteria andCur_tokenGreaterThan(String value) {
            addCriterion("cur_token >", value, "cur_token");
            return (Criteria) this;
        }

        public Criteria andCur_tokenGreaterThanOrEqualTo(String value) {
            addCriterion("cur_token >=", value, "cur_token");
            return (Criteria) this;
        }

        public Criteria andCur_tokenLessThan(String value) {
            addCriterion("cur_token <", value, "cur_token");
            return (Criteria) this;
        }

        public Criteria andCur_tokenLessThanOrEqualTo(String value) {
            addCriterion("cur_token <=", value, "cur_token");
            return (Criteria) this;
        }

        public Criteria andCur_tokenLike(String value) {
            addCriterion("cur_token like", value, "cur_token");
            return (Criteria) this;
        }

        public Criteria andCur_tokenNotLike(String value) {
            addCriterion("cur_token not like", value, "cur_token");
            return (Criteria) this;
        }

        public Criteria andCur_tokenIn(List<String> values) {
            addCriterion("cur_token in", values, "cur_token");
            return (Criteria) this;
        }

        public Criteria andCur_tokenNotIn(List<String> values) {
            addCriterion("cur_token not in", values, "cur_token");
            return (Criteria) this;
        }

        public Criteria andCur_tokenBetween(String value1, String value2) {
            addCriterion("cur_token between", value1, value2, "cur_token");
            return (Criteria) this;
        }

        public Criteria andCur_tokenNotBetween(String value1, String value2) {
            addCriterion("cur_token not between", value1, value2, "cur_token");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_users
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}