package com.samchat.common.beans.auto.db.entitybeans;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TUserUsersChangeableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    public TUserUsersChangeableExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUser_idIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser_idEqualTo(Long value) {
            addCriterion("user_id =", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThan(Long value) {
            addCriterion("user_id >", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThan(Long value) {
            addCriterion("user_id <", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIn(List<Long> values) {
            addCriterion("user_id in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andClient_idIsNull() {
            addCriterion("client_id is null");
            return (Criteria) this;
        }

        public Criteria andClient_idIsNotNull() {
            addCriterion("client_id is not null");
            return (Criteria) this;
        }

        public Criteria andClient_idEqualTo(String value) {
            addCriterion("client_id =", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idNotEqualTo(String value) {
            addCriterion("client_id <>", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idGreaterThan(String value) {
            addCriterion("client_id >", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idGreaterThanOrEqualTo(String value) {
            addCriterion("client_id >=", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idLessThan(String value) {
            addCriterion("client_id <", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idLessThanOrEqualTo(String value) {
            addCriterion("client_id <=", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idLike(String value) {
            addCriterion("client_id like", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idNotLike(String value) {
            addCriterion("client_id not like", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idIn(List<String> values) {
            addCriterion("client_id in", values, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idNotIn(List<String> values) {
            addCriterion("client_id not in", values, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idBetween(String value1, String value2) {
            addCriterion("client_id between", value1, value2, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idNotBetween(String value1, String value2) {
            addCriterion("client_id not between", value1, value2, "client_id");
            return (Criteria) this;
        }

        public Criteria andDevice_idIsNull() {
            addCriterion("device_id is null");
            return (Criteria) this;
        }

        public Criteria andDevice_idIsNotNull() {
            addCriterion("device_id is not null");
            return (Criteria) this;
        }

        public Criteria andDevice_idEqualTo(String value) {
            addCriterion("device_id =", value, "device_id");
            return (Criteria) this;
        }

        public Criteria andDevice_idNotEqualTo(String value) {
            addCriterion("device_id <>", value, "device_id");
            return (Criteria) this;
        }

        public Criteria andDevice_idGreaterThan(String value) {
            addCriterion("device_id >", value, "device_id");
            return (Criteria) this;
        }

        public Criteria andDevice_idGreaterThanOrEqualTo(String value) {
            addCriterion("device_id >=", value, "device_id");
            return (Criteria) this;
        }

        public Criteria andDevice_idLessThan(String value) {
            addCriterion("device_id <", value, "device_id");
            return (Criteria) this;
        }

        public Criteria andDevice_idLessThanOrEqualTo(String value) {
            addCriterion("device_id <=", value, "device_id");
            return (Criteria) this;
        }

        public Criteria andDevice_idLike(String value) {
            addCriterion("device_id like", value, "device_id");
            return (Criteria) this;
        }

        public Criteria andDevice_idNotLike(String value) {
            addCriterion("device_id not like", value, "device_id");
            return (Criteria) this;
        }

        public Criteria andDevice_idIn(List<String> values) {
            addCriterion("device_id in", values, "device_id");
            return (Criteria) this;
        }

        public Criteria andDevice_idNotIn(List<String> values) {
            addCriterion("device_id not in", values, "device_id");
            return (Criteria) this;
        }

        public Criteria andDevice_idBetween(String value1, String value2) {
            addCriterion("device_id between", value1, value2, "device_id");
            return (Criteria) this;
        }

        public Criteria andDevice_idNotBetween(String value1, String value2) {
            addCriterion("device_id not between", value1, value2, "device_id");
            return (Criteria) this;
        }

        public Criteria andTokenIsNull() {
            addCriterion("token is null");
            return (Criteria) this;
        }

        public Criteria andTokenIsNotNull() {
            addCriterion("token is not null");
            return (Criteria) this;
        }

        public Criteria andTokenEqualTo(String value) {
            addCriterion("token =", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotEqualTo(String value) {
            addCriterion("token <>", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThan(String value) {
            addCriterion("token >", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThanOrEqualTo(String value) {
            addCriterion("token >=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThan(String value) {
            addCriterion("token <", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThanOrEqualTo(String value) {
            addCriterion("token <=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLike(String value) {
            addCriterion("token like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotLike(String value) {
            addCriterion("token not like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenIn(List<String> values) {
            addCriterion("token in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotIn(List<String> values) {
            addCriterion("token not in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenBetween(String value1, String value2) {
            addCriterion("token between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotBetween(String value1, String value2) {
            addCriterion("token not between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andServicer_list_state_dateIsNull() {
            addCriterion("servicer_list_state_date is null");
            return (Criteria) this;
        }

        public Criteria andServicer_list_state_dateIsNotNull() {
            addCriterion("servicer_list_state_date is not null");
            return (Criteria) this;
        }

        public Criteria andServicer_list_state_dateEqualTo(Date value) {
            addCriterion("servicer_list_state_date =", value, "servicer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andServicer_list_state_dateNotEqualTo(Date value) {
            addCriterion("servicer_list_state_date <>", value, "servicer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andServicer_list_state_dateGreaterThan(Date value) {
            addCriterion("servicer_list_state_date >", value, "servicer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andServicer_list_state_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("servicer_list_state_date >=", value, "servicer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andServicer_list_state_dateLessThan(Date value) {
            addCriterion("servicer_list_state_date <", value, "servicer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andServicer_list_state_dateLessThanOrEqualTo(Date value) {
            addCriterion("servicer_list_state_date <=", value, "servicer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andServicer_list_state_dateIn(List<Date> values) {
            addCriterion("servicer_list_state_date in", values, "servicer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andServicer_list_state_dateNotIn(List<Date> values) {
            addCriterion("servicer_list_state_date not in", values, "servicer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andServicer_list_state_dateBetween(Date value1, Date value2) {
            addCriterion("servicer_list_state_date between", value1, value2, "servicer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andServicer_list_state_dateNotBetween(Date value1, Date value2) {
            addCriterion("servicer_list_state_date not between", value1, value2, "servicer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andCustomer_list_state_dateIsNull() {
            addCriterion("customer_list_state_date is null");
            return (Criteria) this;
        }

        public Criteria andCustomer_list_state_dateIsNotNull() {
            addCriterion("customer_list_state_date is not null");
            return (Criteria) this;
        }

        public Criteria andCustomer_list_state_dateEqualTo(Date value) {
            addCriterion("customer_list_state_date =", value, "customer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andCustomer_list_state_dateNotEqualTo(Date value) {
            addCriterion("customer_list_state_date <>", value, "customer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andCustomer_list_state_dateGreaterThan(Date value) {
            addCriterion("customer_list_state_date >", value, "customer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andCustomer_list_state_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("customer_list_state_date >=", value, "customer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andCustomer_list_state_dateLessThan(Date value) {
            addCriterion("customer_list_state_date <", value, "customer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andCustomer_list_state_dateLessThanOrEqualTo(Date value) {
            addCriterion("customer_list_state_date <=", value, "customer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andCustomer_list_state_dateIn(List<Date> values) {
            addCriterion("customer_list_state_date in", values, "customer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andCustomer_list_state_dateNotIn(List<Date> values) {
            addCriterion("customer_list_state_date not in", values, "customer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andCustomer_list_state_dateBetween(Date value1, Date value2) {
            addCriterion("customer_list_state_date between", value1, value2, "customer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andCustomer_list_state_dateNotBetween(Date value1, Date value2) {
            addCriterion("customer_list_state_date not between", value1, value2, "customer_list_state_date");
            return (Criteria) this;
        }

        public Criteria andFollow_list_state_dateIsNull() {
            addCriterion("follow_list_state_date is null");
            return (Criteria) this;
        }

        public Criteria andFollow_list_state_dateIsNotNull() {
            addCriterion("follow_list_state_date is not null");
            return (Criteria) this;
        }

        public Criteria andFollow_list_state_dateEqualTo(Date value) {
            addCriterion("follow_list_state_date =", value, "follow_list_state_date");
            return (Criteria) this;
        }

        public Criteria andFollow_list_state_dateNotEqualTo(Date value) {
            addCriterion("follow_list_state_date <>", value, "follow_list_state_date");
            return (Criteria) this;
        }

        public Criteria andFollow_list_state_dateGreaterThan(Date value) {
            addCriterion("follow_list_state_date >", value, "follow_list_state_date");
            return (Criteria) this;
        }

        public Criteria andFollow_list_state_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("follow_list_state_date >=", value, "follow_list_state_date");
            return (Criteria) this;
        }

        public Criteria andFollow_list_state_dateLessThan(Date value) {
            addCriterion("follow_list_state_date <", value, "follow_list_state_date");
            return (Criteria) this;
        }

        public Criteria andFollow_list_state_dateLessThanOrEqualTo(Date value) {
            addCriterion("follow_list_state_date <=", value, "follow_list_state_date");
            return (Criteria) this;
        }

        public Criteria andFollow_list_state_dateIn(List<Date> values) {
            addCriterion("follow_list_state_date in", values, "follow_list_state_date");
            return (Criteria) this;
        }

        public Criteria andFollow_list_state_dateNotIn(List<Date> values) {
            addCriterion("follow_list_state_date not in", values, "follow_list_state_date");
            return (Criteria) this;
        }

        public Criteria andFollow_list_state_dateBetween(Date value1, Date value2) {
            addCriterion("follow_list_state_date between", value1, value2, "follow_list_state_date");
            return (Criteria) this;
        }

        public Criteria andFollow_list_state_dateNotBetween(Date value1, Date value2) {
            addCriterion("follow_list_state_date not between", value1, value2, "follow_list_state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateIsNull() {
            addCriterion("state_date is null");
            return (Criteria) this;
        }

        public Criteria andState_dateIsNotNull() {
            addCriterion("state_date is not null");
            return (Criteria) this;
        }

        public Criteria andState_dateEqualTo(Date value) {
            addCriterion("state_date =", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotEqualTo(Date value) {
            addCriterion("state_date <>", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateGreaterThan(Date value) {
            addCriterion("state_date >", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("state_date >=", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateLessThan(Date value) {
            addCriterion("state_date <", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateLessThanOrEqualTo(Date value) {
            addCriterion("state_date <=", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateIn(List<Date> values) {
            addCriterion("state_date in", values, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotIn(List<Date> values) {
            addCriterion("state_date not in", values, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateBetween(Date value1, Date value2) {
            addCriterion("state_date between", value1, value2, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotBetween(Date value1, Date value2) {
            addCriterion("state_date not between", value1, value2, "state_date");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_users_changeable
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}