package com.skyworld.beans.auto.db.entitybeans;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TSysConfigsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    public TSysConfigsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andParam_idIsNull() {
            addCriterion("param_id is null");
            return (Criteria) this;
        }

        public Criteria andParam_idIsNotNull() {
            addCriterion("param_id is not null");
            return (Criteria) this;
        }

        public Criteria andParam_idEqualTo(Integer value) {
            addCriterion("param_id =", value, "param_id");
            return (Criteria) this;
        }

        public Criteria andParam_idNotEqualTo(Integer value) {
            addCriterion("param_id <>", value, "param_id");
            return (Criteria) this;
        }

        public Criteria andParam_idGreaterThan(Integer value) {
            addCriterion("param_id >", value, "param_id");
            return (Criteria) this;
        }

        public Criteria andParam_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("param_id >=", value, "param_id");
            return (Criteria) this;
        }

        public Criteria andParam_idLessThan(Integer value) {
            addCriterion("param_id <", value, "param_id");
            return (Criteria) this;
        }

        public Criteria andParam_idLessThanOrEqualTo(Integer value) {
            addCriterion("param_id <=", value, "param_id");
            return (Criteria) this;
        }

        public Criteria andParam_idIn(List<Integer> values) {
            addCriterion("param_id in", values, "param_id");
            return (Criteria) this;
        }

        public Criteria andParam_idNotIn(List<Integer> values) {
            addCriterion("param_id not in", values, "param_id");
            return (Criteria) this;
        }

        public Criteria andParam_idBetween(Integer value1, Integer value2) {
            addCriterion("param_id between", value1, value2, "param_id");
            return (Criteria) this;
        }

        public Criteria andParam_idNotBetween(Integer value1, Integer value2) {
            addCriterion("param_id not between", value1, value2, "param_id");
            return (Criteria) this;
        }

        public Criteria andParam_codeIsNull() {
            addCriterion("param_code is null");
            return (Criteria) this;
        }

        public Criteria andParam_codeIsNotNull() {
            addCriterion("param_code is not null");
            return (Criteria) this;
        }

        public Criteria andParam_codeEqualTo(String value) {
            addCriterion("param_code =", value, "param_code");
            return (Criteria) this;
        }

        public Criteria andParam_codeNotEqualTo(String value) {
            addCriterion("param_code <>", value, "param_code");
            return (Criteria) this;
        }

        public Criteria andParam_codeGreaterThan(String value) {
            addCriterion("param_code >", value, "param_code");
            return (Criteria) this;
        }

        public Criteria andParam_codeGreaterThanOrEqualTo(String value) {
            addCriterion("param_code >=", value, "param_code");
            return (Criteria) this;
        }

        public Criteria andParam_codeLessThan(String value) {
            addCriterion("param_code <", value, "param_code");
            return (Criteria) this;
        }

        public Criteria andParam_codeLessThanOrEqualTo(String value) {
            addCriterion("param_code <=", value, "param_code");
            return (Criteria) this;
        }

        public Criteria andParam_codeLike(String value) {
            addCriterion("param_code like", value, "param_code");
            return (Criteria) this;
        }

        public Criteria andParam_codeNotLike(String value) {
            addCriterion("param_code not like", value, "param_code");
            return (Criteria) this;
        }

        public Criteria andParam_codeIn(List<String> values) {
            addCriterion("param_code in", values, "param_code");
            return (Criteria) this;
        }

        public Criteria andParam_codeNotIn(List<String> values) {
            addCriterion("param_code not in", values, "param_code");
            return (Criteria) this;
        }

        public Criteria andParam_codeBetween(String value1, String value2) {
            addCriterion("param_code between", value1, value2, "param_code");
            return (Criteria) this;
        }

        public Criteria andParam_codeNotBetween(String value1, String value2) {
            addCriterion("param_code not between", value1, value2, "param_code");
            return (Criteria) this;
        }

        public Criteria andParam_valueIsNull() {
            addCriterion("param_value is null");
            return (Criteria) this;
        }

        public Criteria andParam_valueIsNotNull() {
            addCriterion("param_value is not null");
            return (Criteria) this;
        }

        public Criteria andParam_valueEqualTo(String value) {
            addCriterion("param_value =", value, "param_value");
            return (Criteria) this;
        }

        public Criteria andParam_valueNotEqualTo(String value) {
            addCriterion("param_value <>", value, "param_value");
            return (Criteria) this;
        }

        public Criteria andParam_valueGreaterThan(String value) {
            addCriterion("param_value >", value, "param_value");
            return (Criteria) this;
        }

        public Criteria andParam_valueGreaterThanOrEqualTo(String value) {
            addCriterion("param_value >=", value, "param_value");
            return (Criteria) this;
        }

        public Criteria andParam_valueLessThan(String value) {
            addCriterion("param_value <", value, "param_value");
            return (Criteria) this;
        }

        public Criteria andParam_valueLessThanOrEqualTo(String value) {
            addCriterion("param_value <=", value, "param_value");
            return (Criteria) this;
        }

        public Criteria andParam_valueLike(String value) {
            addCriterion("param_value like", value, "param_value");
            return (Criteria) this;
        }

        public Criteria andParam_valueNotLike(String value) {
            addCriterion("param_value not like", value, "param_value");
            return (Criteria) this;
        }

        public Criteria andParam_valueIn(List<String> values) {
            addCriterion("param_value in", values, "param_value");
            return (Criteria) this;
        }

        public Criteria andParam_valueNotIn(List<String> values) {
            addCriterion("param_value not in", values, "param_value");
            return (Criteria) this;
        }

        public Criteria andParam_valueBetween(String value1, String value2) {
            addCriterion("param_value between", value1, value2, "param_value");
            return (Criteria) this;
        }

        public Criteria andParam_valueNotBetween(String value1, String value2) {
            addCriterion("param_value not between", value1, value2, "param_value");
            return (Criteria) this;
        }

        public Criteria andParam_descIsNull() {
            addCriterion("param_desc is null");
            return (Criteria) this;
        }

        public Criteria andParam_descIsNotNull() {
            addCriterion("param_desc is not null");
            return (Criteria) this;
        }

        public Criteria andParam_descEqualTo(String value) {
            addCriterion("param_desc =", value, "param_desc");
            return (Criteria) this;
        }

        public Criteria andParam_descNotEqualTo(String value) {
            addCriterion("param_desc <>", value, "param_desc");
            return (Criteria) this;
        }

        public Criteria andParam_descGreaterThan(String value) {
            addCriterion("param_desc >", value, "param_desc");
            return (Criteria) this;
        }

        public Criteria andParam_descGreaterThanOrEqualTo(String value) {
            addCriterion("param_desc >=", value, "param_desc");
            return (Criteria) this;
        }

        public Criteria andParam_descLessThan(String value) {
            addCriterion("param_desc <", value, "param_desc");
            return (Criteria) this;
        }

        public Criteria andParam_descLessThanOrEqualTo(String value) {
            addCriterion("param_desc <=", value, "param_desc");
            return (Criteria) this;
        }

        public Criteria andParam_descLike(String value) {
            addCriterion("param_desc like", value, "param_desc");
            return (Criteria) this;
        }

        public Criteria andParam_descNotLike(String value) {
            addCriterion("param_desc not like", value, "param_desc");
            return (Criteria) this;
        }

        public Criteria andParam_descIn(List<String> values) {
            addCriterion("param_desc in", values, "param_desc");
            return (Criteria) this;
        }

        public Criteria andParam_descNotIn(List<String> values) {
            addCriterion("param_desc not in", values, "param_desc");
            return (Criteria) this;
        }

        public Criteria andParam_descBetween(String value1, String value2) {
            addCriterion("param_desc between", value1, value2, "param_desc");
            return (Criteria) this;
        }

        public Criteria andParam_descNotBetween(String value1, String value2) {
            addCriterion("param_desc not between", value1, value2, "param_desc");
            return (Criteria) this;
        }

        public Criteria andParam_groupIsNull() {
            addCriterion("param_group is null");
            return (Criteria) this;
        }

        public Criteria andParam_groupIsNotNull() {
            addCriterion("param_group is not null");
            return (Criteria) this;
        }

        public Criteria andParam_groupEqualTo(String value) {
            addCriterion("param_group =", value, "param_group");
            return (Criteria) this;
        }

        public Criteria andParam_groupNotEqualTo(String value) {
            addCriterion("param_group <>", value, "param_group");
            return (Criteria) this;
        }

        public Criteria andParam_groupGreaterThan(String value) {
            addCriterion("param_group >", value, "param_group");
            return (Criteria) this;
        }

        public Criteria andParam_groupGreaterThanOrEqualTo(String value) {
            addCriterion("param_group >=", value, "param_group");
            return (Criteria) this;
        }

        public Criteria andParam_groupLessThan(String value) {
            addCriterion("param_group <", value, "param_group");
            return (Criteria) this;
        }

        public Criteria andParam_groupLessThanOrEqualTo(String value) {
            addCriterion("param_group <=", value, "param_group");
            return (Criteria) this;
        }

        public Criteria andParam_groupLike(String value) {
            addCriterion("param_group like", value, "param_group");
            return (Criteria) this;
        }

        public Criteria andParam_groupNotLike(String value) {
            addCriterion("param_group not like", value, "param_group");
            return (Criteria) this;
        }

        public Criteria andParam_groupIn(List<String> values) {
            addCriterion("param_group in", values, "param_group");
            return (Criteria) this;
        }

        public Criteria andParam_groupNotIn(List<String> values) {
            addCriterion("param_group not in", values, "param_group");
            return (Criteria) this;
        }

        public Criteria andParam_groupBetween(String value1, String value2) {
            addCriterion("param_group between", value1, value2, "param_group");
            return (Criteria) this;
        }

        public Criteria andParam_groupNotBetween(String value1, String value2) {
            addCriterion("param_group not between", value1, value2, "param_group");
            return (Criteria) this;
        }

        public Criteria andState_dateIsNull() {
            addCriterion("state_date is null");
            return (Criteria) this;
        }

        public Criteria andState_dateIsNotNull() {
            addCriterion("state_date is not null");
            return (Criteria) this;
        }

        public Criteria andState_dateEqualTo(Date value) {
            addCriterion("state_date =", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotEqualTo(Date value) {
            addCriterion("state_date <>", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateGreaterThan(Date value) {
            addCriterion("state_date >", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("state_date >=", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateLessThan(Date value) {
            addCriterion("state_date <", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateLessThanOrEqualTo(Date value) {
            addCriterion("state_date <=", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateIn(List<Date> values) {
            addCriterion("state_date in", values, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotIn(List<Date> values) {
            addCriterion("state_date not in", values, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateBetween(Date value1, Date value2) {
            addCriterion("state_date between", value1, value2, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotBetween(Date value1, Date value2) {
            addCriterion("state_date not between", value1, value2, "state_date");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Byte value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Byte value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Byte value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Byte value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Byte value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Byte> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Byte> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Byte value1, Byte value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Byte value1, Byte value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_configs
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_configs
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}