package com.skyworld.beans.auto.db.mapper;

import com.skyworld.beans.auto.db.entitybeans.TUserUsers;
import com.skyworld.beans.auto.db.entitybeans.TUserUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    int countByExample(TUserUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    int deleteByExample(TUserUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    int insert(TUserUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    int insertSelective(TUserUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    List<TUserUsers> selectByExample(TUserUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    TUserUsers selectByPrimaryKey(Long user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TUserUsers record, @Param("example") TUserUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TUserUsers record, @Param("example") TUserUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TUserUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_users
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TUserUsers record);
}